### ISSUE TITLE
configuration: Does not update after changing joint position (and calling `prepare` explicitly)

### ISSUE THREAD

**Issue by Ondraceq** [paradise-fi/RoFI#101]
I created #100 to demonstrate the bug.
When calling `rofi-tool preview data/configurations/init.in 0` and `rofi-tool preview data/configurations/init.in 1`, the output should be the same (see the changes in the code). - But it's not.

**Comment by jajik** [comment]
The bug should be fixed in the commit above. I've created PR and requested a review.

**Comment by Ondraceq** [comment]
Solved by #102
