### ISSUE TITLE
configuration: `Rofibot::isValid` throws

### ISSUE THREAD

**Issue by Ondraceq** [paradise-fi/RoFI#153]
```
Rofibot bot;
bot.insert( UniversalModule( 1, 0_deg, 0_deg, 0_deg ) );
bot.insert( UniversalModule( 2, 0_deg, 0_deg, 0_deg ) );
bot.prepare();
bot.isValid();
```
throws exception with message `Module is not prepared`.

**Comment by jajik** [comment]
`prepare` throws correctly because the modules are not connected to any point in space. The message is different though `Not fixed position of module 1`.

**Comment by Ondraceq** [comment]
^ Was already fixed. The problem was that `prepare` didn't check that the modules were fixed in space, so it left the Rofibot in inconsistent state.
