### ISSUE TITLE
configuration: Add documentation for configuration

### ISSUE THREAD

**Issue by jajik** [paradise-fi/RoFI#172]
Currently, there is a generated doxygen for legacy configuration only. Build documentation for the current configuration and consider dropping the old one (check how useful it is).

**Comment by Ondraceq** [comment]
I created #179 and put there some basic documentation.
It would be great if you (@jajik) could add the accompanying text and if you could document the serialization.
With the serialization I'm not even sure where to look for info if I don't want to look into the parsing code itself.

**Comment by Ondraceq** [comment]
Also it should be done at most at the 10th of May for the presentation of simplesim.

**Comment by jajik** [comment]
Docs are part of #182
