### ISSUE TITLE
Configurable build system

### ISSUE THREAD

**Issue by xbarnat** [paradise-fi/RoFI#20]
I believe we need to add some configuration to the build system. So that user may set up installation dir, or enable/disable components to be built. I would appreciate a single directory with binaries so that I can add that path to my $PATH environment variable.

**Comment by yaqwsx** [comment]
Partially addressed in #38. What is missing:
- [ ] the user can select whether use system Z3 or build a custom version of Z3 for SMT reconfig

**Comment by yaqwsx** [comment]
Solved in d675f91
