### ISSUE TITLE
configuration: Rename `Rofibot` to `RofiWorld` (or something similar)

### ISSUE THREAD

**Issue by Ondraceq** [paradise-fi/RoFI#214]
`Rofibot` seems to mislead the users to think about the world as composed from multiple `Rofibot`s.
The usage that we have is that one `Rofibot` is the whole world, so it doesn't make sense to have two `Rofibot`s in one simulation.

I believe that `RofiWorld` expresses this view better (and I convinced @yaqwsx about this as well).

**Comment by jajik** [comment]
I don't have, but I will do it.

**Comment by Ondraceq** [comment]
Ok, I didn't know that. Thanks

**Comment by Ondraceq** [comment]
Fixed by #248
