### ISSUE TITLE
Configuration -- fix findEdge bug

### ISSUE THREAD

**Issue by Trphajzlik** [paradise-fi/RoFI#46]
Right now we are only checking whether there exists edge on the spot. We do not check if the edges are same.

**Comment by jtojnar** [comment]
24351e37630517e0550befec0e2a43cacb70a1c0 fixed that, making the `findEdge` method identical to `findConnection`. Maybe we should remove one of them – unless `findEdge` was meant to find an existing edge starting from the same connector as the `edge` passed to it when it was introduced in https://github.com/paradise-fi/RoFI/commit/c751cd7e8af965b03eaf09f07969908f91af2984.

**Comment by yaqwsx** [comment]
There is a new configuration representation and all the tools are slowly migrating to it.
